replicaCount: 2
prometheus:
  enabled: false   # disabled until kube-prom-stack CRDs ready
webhook:
  replicaCount: 2
cainjector:
  replicaCount: 2
extraArgs:
  - "--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53"
  - "--dns01-recursive-nameservers-only"
