{{- $v := include "microservice.merged" . | fromYaml -}}
{{- if and $v.database.enabled $v.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "microservice.fullname" . }}-db
  labels: {{- include "microservice.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $v.externalSecret.refreshInterval }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ include "microservice.fullname" . }}-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ $v.externalSecret.awsSecretPath | quote }}
        property: DATABASE_URL
{{- end }}
