apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-stable
  labels: {{- include "microservice.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "microservice.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
